version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.ml.enabled=true"
      - "xpack.watcher.enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    restart: always
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"      
    links:
      - elasticsearch
    depends_on: 
      - elasticsearch

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro,Z
      - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users:ro,Z
    ports:
      - "80:80"
    links:
      - kibana
    depends_on:
      - kibana
