version: '2'

volumes:

  elasticsearch_data:
    driver: local
    
  elasticsearch2_data:
    driver: local

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    restart: always
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    restart: always
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.zen.ping.unicast.hosts: elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch2_data:/usr/share/elasticsearch/data     
    links:
      - elasticsearch
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    restart: always
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"      
    links:
      - elasticsearch
    depends_on: 
      - elasticsearch

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro,Z
      - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users:ro,Z
    ports:
      - "80:80"
    links:
      - kibana
    depends_on:
      - kibana
